### ISSUE TITLE
prereq: provision Windows machines

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/docker-exercises#40]
Preparations: 
AWS machine, (windows with containers machine)
* Docker
* visual studio

**Comment by Sharor** [comment]
We need : 

Docker (There is an AWS ami you can use!) 
and git bash instead  of visual studio. (so only thing that needs to be put on top is git bash)

**Comment by Sharor** [comment]
@meekrosoft I hope the git bash part is ok, otherwise I guess we can ship the machines with the binary for git bash and have them install it

**Comment by sami-alajrami** [comment]
Not sure if the scripts should be in this repo or not, so I created a new repo with
terraform and packer scripts : https://github.com/Praqma/provision-win-docker
instructions are there too .. the packer build takes ~10 minutes, so should be done in advance.

**Comment by meekrosoft** [comment]
@Sharor can you test this is sufficient for the training?

**Comment by Sharor** [comment]
I will, just talked to Sofus about this :) @meekrosoft 

@sami-alajrami I think its good to put it here - I failed to mention that I may have some disk requirements, since docker images for windows are,.. huge. 

Im using a 50 gb disk right now, and its almost completely full from the examples I run. 

Ill try to verify either today or tomorrow, and give you a shout 😉  Cheers dude and thanks for helping!
