### ISSUE TITLE
prereq: Linux machines

### ISSUE THREAD

**Issue by sofusalbertsen** [praqma-training/docker-exercises#41]
Linux machines
* Docker
* Docker-compose
* K8s

For K8s

1 master machine
2 nodes with cubeadm on it.

**Comment by Sharor** [comment]
k8s kubeadm installation: 
sudo -i
apt-get update && apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb http://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -y kubelet kubeadm kubectl

**Comment by Sharor** [comment]
They all need to have port 6443 open, since I don't know which master people will choose.

**Comment by Sharor** [comment]
Probably also all need access to port 80

**Comment by Sharor** [comment]
Scratch this - I dont need any of this since we are taking a different approach. 

@sami-alajrami 

I may need the google sdk, do you think you can help me set that up if needed ? We're running a bit tight on time, but I hope we can talk tomorrow when me and Sofus go through the material? 

I have instructions for whats needed, I just need your help implementing it.

**Comment by sami-alajrami** [comment]
@Sharor I am afraid I am occupied till the end of the week .. if you give me more information on whats needed, I can see if I can fit it somewhere tomorrow evening

**Comment by Sharor** [comment]
@sami-alajrami we're running everything so far as it should be, and I think we're good :) thanks though !
